const actionTypeConstants = {
    INIT: "INIT",
    PROVIDER_DETAILS: 'PROVIDER_DETAILS',
    DASHBOARD_DETAILS: "DASHBOARD_DETAILS",
    CLIENT_REVIEW_DETAILS:"CLIENT_REVIEW_DETAILS"
}
export default actionTypeConstants;