const componentTypes = {
    TYPOGRAPHY: 'TYPOGRAPHY',
    CARD: 'CARD',
    NAVIGATE_BUTTON: 'NAVIGATE_BUTTON',
    IMAGE: 'IMAGE',
    PROGRESSBAR: 'PROGRESSBAR',
    STATUS_BUTTON: 'STATUS_BUTTON',
    LIST: 'LIST',
    ICON: 'ICON',
    FORM: 'FORM',
    DROPDOWN: 'DROPDOWN',
    PLAIN_BUTTON: 'PLAIN_BUTTON',
    VIDEO: 'VIDEO',
    DATEPICKER: 'DATEPICKER',
    LIST_ITEMS: 'LIST_ITEMS',
    LINE_ITEMS: 'LINE_ITEMS',
    SEARCH_FIELD: 'SEARCH_FIELD',
}

export default componentTypes
