import {
  Dashboard,
  Home,
  Instructions,
  Login,
  OtpVerify,
  Splashscreen,
  ReferralPartner,
  WelcomeScreen,
  IntroSliderScreen,
  LeadSpend,
  CostPerLead,
  Customers,
  ReferralStatus,
  ContactLeads,
  ExclusiveReferral,
  ClientReviews,
  Profile,
  JoinMovingFull,
  UploadAndDisplayLogo,
  GetStarted,
} from '../templates';

const Library = {
  introslider: IntroSliderScreen,
  welcome: WelcomeScreen,
  home: Home,
  splash: Splashscreen,
  login: Login,
  otpverify: OtpVerify,
  dashboard: Dashboard,
  instructions: Instructions,
  referralpartner: ReferralPartner,
  'contact-leads': ContactLeads,
  leadspend: LeadSpend,
  costperlead: CostPerLead,
  customers: Customers,
  referralstatus: ReferralStatus,
  exclusivereferral: ExclusiveReferral,
  reviews: ClientReviews,
  'my-profile': Profile,
  signUp: JoinMovingFull,
  'upload-logo': UploadAndDisplayLogo,
  congratulations: Instructions,
  'stripe-info': Instructions,
  getStarted: GetStarted,
};

export default Library;
