//import Config from "react-native-config";
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.


const config = {
    "wip": {
        Auth: {
            mandatorySignIn: true,
            region: 'ap-south-1',
            userPoolId: 'ap-south-1_JKdZzIhUm',
            userPoolWebClientId: '7g89pqnp5qeshmbjpvdko8btsv',
            authenticationFlowType: 'CUSTOM_AUTH',
            oauth: {}
        },
        aws_appsync_apiKey: "da2-34h3af5rzvf6lnlcxtz3ve3wgq	",
        aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
        aws_appsync_region: 'ap-south-1',
        aws_appsync_graphqlEndpoint: 'https://cmv7odwoonagzdqhuojkazfu6m.appsync-api.ap-south-1.amazonaws.com/graphql'
    },
    "uat": {
        Auth: {
            mandatorySignIn: true,
            region: 'us-east-1',
            userPoolId: 'us-east-1_z7nGKmCyP',
            userPoolWebClientId: '4df1hsh5j7qtqs22h4f729t3t9',
            authenticationFlowType: 'CUSTOM_AUTH',
            oauth: {}
        },
        aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
        aws_appsync_region: 'us-east-1',
        aws_appsync_graphqlEndpoint: 'https://36hxcoie7nffhclcwq5hd3uhwu.appsync-api.us-east-1.amazonaws.com/graphql'
    },
    "alpha": {
        Auth: {
            mandatorySignIn: true,
            region: 'us-east-1',
            userPoolId: 'us-east-1_sNo1EN4WX',
            userPoolWebClientId: '2dlre3h38gvf95iirkd57uv3n',
            authenticationFlowType: 'CUSTOM_AUTH',
            oauth: {}
        },
        aws_appsync_apiKey: 'da2-xoonzhfozfhvbjxya3hc47z2te',
        aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
        aws_appsync_region: 'us-east-1',
        aws_appsync_graphqlEndpoint: 'https://al4gka3yjvggtgxnatqsnymiem.appsync-api.us-east-1.amazonaws.com/graphql'
    },
    "beta": {
        Auth: {
            mandatorySignIn: true,
            region: 'us-east-1',
            userPoolId: 'us-east-1_4dImvKa8y',
            userPoolWebClientId: '47e1205vsj5q9dqu16ga8fgrse',
            authenticationFlowType: 'CUSTOM_AUTH',
            oauth: {}
        },
        aws_appsync_apiKey: 'da2-co25sax27zcetpow4kgucv475e',
        aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
        aws_appsync_region: 'us-east-1',
        aws_appsync_graphqlEndpoint: 'https://p26vvnnhnfg5zo4qcyodxfe6si.appsync-api.us-east-1.amazonaws.com/graphql'
    },
    "prod": {
        Auth: {
            mandatorySignIn: true,
            region: 'us-east-1',
            userPoolId: 'us-east-1_DBoye88zw',
            userPoolWebClientId: '43pt6406d3msnh4sajpgm17hqq',
            authenticationFlowType: 'CUSTOM_AUTH',
            oauth: {}
        },
        aws_appsync_apiKey:'da2-v2rd6cgfonfwdi57epcq7n2doe',
        aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
        aws_appsync_region: 'us-east-1',
        aws_appsync_graphqlEndpoint: 'https://ukfijfecjzc2dcqawggti3jk5i.appsync-api.us-east-1.amazonaws.com/graphql'
    } 
}

export default config["wip"];
